channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base 
  - bioconda::bioconductor-phyloseq 
  - conda-forge::r-dplyr 
  - conda-forge::r-ggplot2 
  - conda-forge::r-scales 
  - bioconda::bioconductor-microbiome 
  - conda-forge::r-vegan 
  - conda-forge::r-ggrepel
